server:
  port: 8080
spring:
  application:
    name: git_minus
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://****:3306/repo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ****
      password: ***
  mail:
    host: smtp.qq.com
    port: 465
    username: ***
    password: ***
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
ftp:
  protocol: sftp
  port: 22
  address: ****
  username: ***
  password: ***
  config:
    StrictHostKeyChecking: no
remote-repo-path: /mydata/git_repo
